default:
  outputs:
    dev:
      type: trino
      host: trino-coordinator
      port: 8080
      user: dbt
      database: hive
      schema: default # overridden in models
      threads: 1
  target: dev
